# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cart.proto',
  package='cart',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncart.proto\x12\x04\x63\x61rt\"\x1a\n\x0bItemRequest\x12\x0b\n\x03key\x18\x01 \x01(\x03\"\'\n\tItemReply\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\nItemStatus\x12\x0e\n\x06result\x18\x01 \x01(\t2l\n\x07Shopper\x12/\n\x07GetItem\x12\x11.cart.ItemRequest\x1a\x0f.cart.ItemReply\"\x00\x12\x30\n\tWriteItem\x12\x0f.cart.ItemReply\x1a\x10.cart.ItemStatus\"\x00\x62\x06proto3'
)




_ITEMREQUEST = _descriptor.Descriptor(
  name='ItemRequest',
  full_name='cart.ItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cart.ItemRequest.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=46,
)


_ITEMREPLY = _descriptor.Descriptor(
  name='ItemReply',
  full_name='cart.ItemReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cart.ItemReply.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='cart.ItemReply.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=87,
)


_ITEMSTATUS = _descriptor.Descriptor(
  name='ItemStatus',
  full_name='cart.ItemStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cart.ItemStatus.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['ItemRequest'] = _ITEMREQUEST
DESCRIPTOR.message_types_by_name['ItemReply'] = _ITEMREPLY
DESCRIPTOR.message_types_by_name['ItemStatus'] = _ITEMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemRequest = _reflection.GeneratedProtocolMessageType('ItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMREQUEST,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.ItemRequest)
  })
_sym_db.RegisterMessage(ItemRequest)

ItemReply = _reflection.GeneratedProtocolMessageType('ItemReply', (_message.Message,), {
  'DESCRIPTOR' : _ITEMREPLY,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.ItemReply)
  })
_sym_db.RegisterMessage(ItemReply)

ItemStatus = _reflection.GeneratedProtocolMessageType('ItemStatus', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSTATUS,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.ItemStatus)
  })
_sym_db.RegisterMessage(ItemStatus)



_SHOPPER = _descriptor.ServiceDescriptor(
  name='Shopper',
  full_name='cart.Shopper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetItem',
    full_name='cart.Shopper.GetItem',
    index=0,
    containing_service=None,
    input_type=_ITEMREQUEST,
    output_type=_ITEMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WriteItem',
    full_name='cart.Shopper.WriteItem',
    index=1,
    containing_service=None,
    input_type=_ITEMREPLY,
    output_type=_ITEMSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOPPER)

DESCRIPTOR.services_by_name['Shopper'] = _SHOPPER

# @@protoc_insertion_point(module_scope)
