# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cart_pb2 as cart__pb2


class ShopperStub(object):
    """The shopping cart service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/cart.Shopper/GetItem',
                request_serializer=cart__pb2.ItemRequest.SerializeToString,
                response_deserializer=cart__pb2.ItemReply.FromString,
                )
        self.WriteItem = channel.unary_unary(
                '/cart.Shopper/WriteItem',
                request_serializer=cart__pb2.ItemReply.SerializeToString,
                response_deserializer=cart__pb2.ItemStatus.FromString,
                )


class ShopperServicer(object):
    """The shopping cart service definition.
    """

    def GetItem(self, request, context):
        """Writes a Key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteItem(self, request, context):
        """Writes a Key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=cart__pb2.ItemRequest.FromString,
                    response_serializer=cart__pb2.ItemReply.SerializeToString,
            ),
            'WriteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteItem,
                    request_deserializer=cart__pb2.ItemReply.FromString,
                    response_serializer=cart__pb2.ItemStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cart.Shopper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shopper(object):
    """The shopping cart service definition.
    """

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cart.Shopper/GetItem',
            cart__pb2.ItemRequest.SerializeToString,
            cart__pb2.ItemReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cart.Shopper/WriteItem',
            cart__pb2.ItemReply.SerializeToString,
            cart__pb2.ItemStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
